### ISSUE TITLE
Update to support Angular 18?

### ISSUE THREAD

**Issue by revisvv** [lVlyke/lithium-angular#39]
Hello!

I've been using [lithium-ngx-virtual-scroll](https://github.com/lVlyke/lithium-ngx-virtual-scroll) on my project, but since updating to Angular 18 I can't run `npm install` without `--legacy-peer-deps` flag. 

> npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=11.0.0 <18.0.0" from @lithiumjs/angular@7.3.1
npm ERR! node_modules/@lithiumjs/angular
npm ERR!   @lithiumjs/angular@"^7.3.1" from the root project
npm ERR!   peer @lithiumjs/angular@">=7.0.0" from @lithiumjs/ngx-virtual-scroll@0.3.1
npm ERR!   node_modules/@lithiumjs/ngx-virtual-scroll
npm ERR!     @lithiumjs/ngx-virtual-scroll@"^0.3.1" from the root project

Any plans for an update? Thanks!

**Comment by lVlyke** [comment]
Version 8.0.0 has been released which adds Angular 18 support (as well as version 0.3.2 of @lithiumjs/ngx-virtual-scroll).
